repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: no-commit-to-branch
	  - id: check-merge-conflict
  - repo: local
     hooks:
      - id: flake8
        name: flake8
        entry: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        entry: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: pytest
        always_run: true
