name: census_fastAPI
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas
  - pip
  - pytest
  - flake8
  - pip:
    - awscli==1.22.23
    - dvc
    - dvc[s3]
    - fastapi==0.70.1
    - uvicorn
