name: ml-proj-3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  - pytest =6
  - pip:
    - awscli==1.22.23
    - dvc
    - dvc[s3]
    - fastapi==0.70.1
    - uvicorn
