name: ml-proj-3
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - jupyter
  - pytest =6
  - pip:
    - awscli==1.22.23
    - aiobotocore==2.0.1
    - botocore=1.22.8
    - dvc==2.9.2
    - dvc[s3]
    - fastapi==0.70.1
    - uvicorn==0.16.0
