stages:
  split_data:
    cmd: python ml/split_data.py
    deps:
    - data/census.csv
    - ml/split_data.py
    params:
    - modeling.random_state
    - modeling.test_size
    outs:
    - data/test_data.csv
    - data/trainval_data.csv
  process_data:
    cmd: python ml/process_data.py
    deps:
    - data/trainval_data.csv
    - ml/process_data.py
    params:
    - cat_features
    - label
    - train.true_
    outs:
    - data/X.npy
    - data/y.npy
    - model/encoder.pkl
    - model/lb.pkl
  kfold:
    cmd: python ml/kfold.py
    deps:
    - data/trainval_data.csv
    - ml/kfold.py
    params:
    - modeling.n_splits
    - modeling.random_state
    - modeling.shuffle
    metrics:
    - metrics/kfold_scores.json:
        cache: false
  train_predict:
    cmd: python ml/train_predict.py
    deps:
    - data/X.npy
    - data/y.npy
    - ml/train_predict.py
    params:
    - modeling.random_state
    - modeling.test_size
    outs:
    - model/model.pkl
    metrics:
    - metrics/model_scores.json:
        cache: false
    - metrics/precision.json:
        cache: false
    - metrics/roc.json:
        cache: false
  slice_predict:
    cmd: python ml/slice_predict.py
    deps:
    - ml/slice_predict.py
    - data/trainval_data.csv
    - model/encoder.pkl
    - model/lb.pkl
    - model/model.pkl
    params:
    - cat_features
    - label
    - train.false_
    outs:
    - metrics/slice_scores.json
