main:
  project_name: census
  experiment_name: dev
modeling:
  n_splits: 8 
  shuffle: True
  random_state: 1
  max_iter: 250
  test_size: .1
metrics: 
  beta: 1
  zero_division: 1
  roc: 'metrics/roc.json'
  precision: 'metrics/precision.json'
  model: 'metrics/model_scores.json'
  kfold: 'metrics/kfold_scores.json'
  slice_scores: 'metrics/slice_scores.json'
data:
  clean_data: 'data/clean_data.csv'
  raw_data: 'data/census.csv'
  test_data: 'data/test_data.csv'
  trainval_data: 'data/trainval_data.csv'
  X: 'data/X.npy'
  y: 'data/y.npy'
model:
  model_pth: 'model/model.pkl' 
  encoder_pth: 'model/encoder.pkl' 
  lb_pth: 'model/lb.pkl' 
cat_features: [
        "workclass",
        "education",
        "marital-status",
        "occupation",
        "relationship",
        "race",
        "sex",
        "native-country",
    ]
train:
  true_: True
  false_: False
label: 'salary'
