main:
  project_name: census
  experiment_name: dev
  model_pth: '../model/' 
modeling:
  n_splits: 5 
  shuffle: True
  random_state: 42
  max_iter: 150
  test_size: .2
metrics: 
  dir: '../metrics/'
  roc: 'roc_curve.png'
  beta: 1
  zero_division: 1
data:
  dir: '../data/'
  cleaned_data: 'cleaned_data.csv'
  raw_data: 'census.csv'
