main:
  project_name: census
  experiment_name: dev
modeling:
  n_splits: 5 
  shuffle: True
  random_state: 42
  max_iter: 150
  test_size: .2
metrics: 
  dir: '../metrics/'
  roc: 'roc_curve.png'
  beta: 1
  zero_division: 1
data:
  clean_data: '../data/clean_data.csv'
  raw_data: '../data/census.csv'
  test_data: '../data/test_data.csv'
  model_pth: '../model/model.pkl' 
  encoder_pth: '../model/encoder.pkl' 
  lb_pth: '../model/lb.pkl' 
